export enum SVG {
    Euro = "Euro",
    Trash = "Trash",
    Dollar = "Dollar",
    DropdownArrow = "DropdownArrow",
    LockClosed = "LockClosed",
    LockOpen = "LockOpen",
    Info = "Info",
    Pounds = "Pounds",
    Question = "Question",
    Search = "Search",
    Cross = "Cross",
    Confirm = "Confirm",
    Pencil = "Pencil",
}