export enum SVG {
    Euro          = "Euro",
    Trash         = "Trash",
    Dollar        = "Dollar",
    DropdownArrow = "DropdownArrow",
    LockClosed    = "LockClosed",
    LockOpen      = "LockOpen",
    Info          = "Info",
    Pounds        = "Pounds",
    Question      = "Question",
    Search        = "Search",
    Cross         = "Cross",
    Checkmark     = "Checkmark",
    Pencil        = "Pencil",
    MoreDots      = "MoreDots",
    InfoSquere    = "InfoSquere",
    InfoCircle    = "InfoCircle",
    HoneyHive     = "HoneyHive",
    Home          = "Home",
    Apiaries      = "Apiaries",
    Calendar      = "Calendar",
    Key           = "Key",
    Plus          = "Plus",
    Restart       = "Restart",
    Cog           = "Cog",
    Profile       = "Profile",
    Logout        = "Logout",
    Save          = "Save",
    ArrowRight    = "ArrowRight",
    BeeHive       = "BeeHive",
    Apiary        = "Apiary",
    Hive          = "Hive"
}

export enum IconType {
    SMALL,
    MEDIUM,
    BIG,
    OTHER
}